/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mulakating;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Burcu
 */
public class girisyapmaekrani extends javax.swing.JFrame {

    
    public ResultSet result_set;
    /**
     * veritabani eklenecek*
     */
    public static Connection baglanti; 
    private ResultSet res;
    /**
     *
     */
    public String link = "jdbc:mysql://134.209.237.235:3306/kayit_form?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=UTC";
    public String kullanici_adi = "root";
    public String sifre = "P@ssW0rd";

    private Object jOptionPane;

    /**
     * Creates new form girisYapmaEkrani
     */
    public girisyapmaekrani() {
        
        initComponents();

        /**
         * veritabani eklenecek*
         */
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtex_kullanici_adi = new javax.swing.JTextField();
        jtex_sifre = new javax.swing.JPasswordField();
        button_giris = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        button_uyelik = new javax.swing.JButton();
        button_temizle = new javax.swing.JButton();
        jlKad = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ÜYE GİRİŞ");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jtex_kullanici_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_kullanici_adiActionPerformed(evt);
            }
        });

        jtex_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_sifreActionPerformed(evt);
            }
        });

        button_giris.setBackground(new java.awt.Color(0, 84, 140));
        button_giris.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        button_giris.setForeground(new java.awt.Color(255, 255, 255));
        button_giris.setText("Giriş Yap");
        button_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_girisActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBox1.setText("Şifremi Göster");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        button_uyelik.setBackground(new java.awt.Color(0, 84, 140));
        button_uyelik.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        button_uyelik.setForeground(new java.awt.Color(255, 255, 255));
        button_uyelik.setText("Üyeliğiniz Yok mu?/Kayıt Olun");
        button_uyelik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_uyelikActionPerformed(evt);
            }
        });

        button_temizle.setBackground(new java.awt.Color(0, 84, 140));
        button_temizle.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        button_temizle.setForeground(new java.awt.Color(255, 255, 255));
        button_temizle.setText("TEMİZLE");
        button_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_temizleActionPerformed(evt);
            }
        });

        jlKad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlKad.setIcon(new javax.swing.ImageIcon("C:\\Users\\Burcu\\Desktop\\16x16-free-application-icons\\png\\16x16\\Person.png")); // NOI18N
        jlKad.setText("Kullanıcı Adı:");

        jlPass.setBackground(new java.awt.Color(0, 0, 0));
        jlPass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPass.setIcon(new javax.swing.ImageIcon("C:\\Users\\Burcu\\Desktop\\16x16-free-application-icons\\png\\16x16\\Key.png")); // NOI18N
        jlPass.setText("Şifre:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("                 ÜYE GİRİŞİ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(button_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(button_uyelik, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPass, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlKad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtex_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jtex_kullanici_adi)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jCheckBox1)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtex_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlKad))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtex_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jlPass))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_uyelik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(button_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_temizleActionPerformed
        // TODO add your handling code here:
        jtex_kullanici_adi.setText("");
        jtex_sifre.setText("");

    }//GEN-LAST:event_button_temizleActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jtex_sifre.setEchoChar((char)0);
        } else {
            jtex_sifre.setEchoChar('#');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void button_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_girisActionPerformed
   
        //giriş işlemleri yürütülür..
        String kullanici_adi = jtex_kullanici_adi.getText();
        String sifre =new String(jtex_sifre.getPassword());
         baglanti_olustur();
        //ekle();
        bul();
        
        try {
            if  (kullanici_adi.isEmpty() || sifre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kullanıcı adı veya Şifre Bölümü Boş..", "Hata", JOptionPane.QUESTION_MESSAGE);
              
            } else if (kullanici_adi.equals(result_set.getString("kullanici_adi")) && sifre.equals(result_set.getString("sifre"))) {
                JOptionPane.showMessageDialog(null, "Hoşgeldiniz ", "Giriş Başarılı", JOptionPane.PLAIN_MESSAGE);
              new genelbakis().setVisible(true);   
              dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Kullanıcı adı veya Şifre Bölümü Hatalı..", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(girisyapmaekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            //** jlKad.setToolTipText("Kullanıcı Adı");
    baglanti_kapat();
    }//GEN-LAST:event_button_girisActionPerformed

    private void jtex_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_sifreActionPerformed

    private void jtex_kullanici_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_kullanici_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_kullanici_adiActionPerformed

    private void button_uyelikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_uyelikActionPerformed
        // TODO add your handling code here:
        kayitFormu kyt = new kayitFormu();
        kyt.setVisible(true);
        kyt.pack();
        kyt.setLocationRelativeTo(null);
        kyt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_button_uyelikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisyapmaekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisyapmaekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisyapmaekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisyapmaekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new girisyapmaekrani().setVisible(true);
            }
        });
    }

    public void baglanti_olustur() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            baglanti = DriverManager.getConnection(link, kullanici_adi, sifre);
           // JOptionPane.showMessageDialog(null, "Bağlanti başarılı");
            String username = jtex_kullanici_adi.getText();
            String password = jtex_sifre.getText();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(girisyapmaekrani.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(girisyapmaekrani.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void baglanti_kapat() {
        try {
            baglanti.close();
        } catch (SQLException ex) {
            Logger.getLogger(girisyapmaekrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  /*  public void ekle() {
        String t1, t2;
        t1 = jtex_kullanici_adi.getText();
        t2 = jtex_sifre.getText();

        String eklesorgusu = "INSERT INTO kayit(kullanici_adi,sifre) values ('"+t1+"','" +t2+"')";
        try {
            Statement abc = baglanti.createStatement();
            abc.execute(eklesorgusu);
            System.out.println("veritabanına veri eklendi");
        } catch (SQLException ex) {
            System.out.println(ex.toString());
            System.out.println("veritabanına veri eklenemedi");
        }
    }*/
    public void bul(){
         try{
            Statement sta=baglanti.createStatement();
            String bulkomutu = "SELECT* FROM kayit WHERE kullanici_adi = '"+jtex_kullanici_adi.getText()+"'";
            
            result_set = sta.executeQuery(bulkomutu);
            result_set.next();    
             }catch(SQLException b){
            System.out.println("Kayıt Bulunurken Hata Oluştu"+b);
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_giris;
    private javax.swing.JButton button_temizle;
    private javax.swing.JButton button_uyelik;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlKad;
    private javax.swing.JLabel jlPass;
    private javax.swing.JTextField jtex_kullanici_adi;
    private javax.swing.JPasswordField jtex_sifre;
    // End of variables declaration//GEN-END:variables

}
  
