/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mulakating;

import static com.mycompany.mulakating.kayitFormu.baglanti;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Burcu
 */
public class kayitFormu extends javax.swing.JFrame {

    public static Connection baglanti;

    /**
     *
     */
    public String link ="jdbc:mysql://134.209.237.235:3306/kayit_form?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=UTC";
    public String kullanici_adi = "root"; 
    public String sifre = "P@ssW0rd";

   //fotoğraf bağlantısı kurmak için değişken oluşturulur
    
    String yol=null;
    
    

    private Object jOptionPane;
    
    public kayitFormu() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_telefon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        button_kaydol = new javax.swing.JButton();
        button_temizle = new javax.swing.JButton();
        button_kapat = new javax.swing.JButton();
        jtex_isim = new javax.swing.JTextField();
        jtex_soyisim = new javax.swing.JTextField();
        jtex_meslek = new javax.swing.JTextField();
        jtex_email = new javax.swing.JTextField();
        jtex_kullanici_adi = new javax.swing.JTextField();
        jlabel_girisegider = new javax.swing.JLabel();
        jl_cinsiyet = new javax.swing.JLabel();
        jradio_kadın = new javax.swing.JRadioButton();
        jradio_erkek = new javax.swing.JRadioButton();
        jtex_tc = new javax.swing.JTextField();
        tc_kimlik = new javax.swing.JLabel();
        jtex_sifre = new javax.swing.JTextField();
        jtex_sifre_tekrar = new javax.swing.JTextField();
        jformtex_dogum = new javax.swing.JFormattedTextField();
        jtex_telefon = new javax.swing.JTextField();
        jcombo_il = new javax.swing.JComboBox<>();

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAYIT FORM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                        KAYIT OLMA FORMU   ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("İSİM :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("SOYİSİM:");

        jl_telefon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_telefon.setText("TELEFON:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("MESLEK:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("YAŞANILAN İL:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("DOĞUM TARİHİ:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("KULLANICI ADI:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("ŞİFRE BELİRLEYİN:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("ŞİFREYİ TEKRAR GİRİN:");

        button_kaydol.setBackground(new java.awt.Color(0, 84, 140));
        button_kaydol.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        button_kaydol.setForeground(new java.awt.Color(255, 255, 255));
        button_kaydol.setText("KAYIT OL");
        button_kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kaydolActionPerformed(evt);
            }
        });

        button_temizle.setBackground(new java.awt.Color(0, 84, 140));
        button_temizle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        button_temizle.setForeground(new java.awt.Color(255, 255, 255));
        button_temizle.setText("TEMİZLE");
        button_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_temizleActionPerformed(evt);
            }
        });

        button_kapat.setBackground(new java.awt.Color(0, 84, 140));
        button_kapat.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        button_kapat.setForeground(new java.awt.Color(255, 255, 255));
        button_kapat.setText("KAPAT");
        button_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kapatActionPerformed(evt);
            }
        });

        jtex_isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_isimActionPerformed(evt);
            }
        });

        jtex_meslek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_meslekActionPerformed(evt);
            }
        });

        jtex_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_emailActionPerformed(evt);
            }
        });

        jlabel_girisegider.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jlabel_girisegider.setForeground(new java.awt.Color(255, 0, 51));
        jlabel_girisegider.setText("ÜYE GİRİŞ EKRANI İÇİN TIKLAYIN");
        jlabel_girisegider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_girisegiderMouseClicked(evt);
            }
        });

        jl_cinsiyet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_cinsiyet.setText("Cinsiyet:");

        buttonGroup1.add(jradio_kadın);
        jradio_kadın.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jradio_kadın.setText(" KADIN");
        jradio_kadın.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_kadınActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradio_erkek);
        jradio_erkek.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jradio_erkek.setText(" ERKEK");

        jtex_tc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtex_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_tcActionPerformed(evt);
            }
        });

        tc_kimlik.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tc_kimlik.setText("T.C Kimlik No:");

        jtex_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtex_sifreActionPerformed(evt);
            }
        });

        try {
            jformtex_dogum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtex_telefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtex_telefonKeyTyped(evt);
            }
        });

        jcombo_il.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adana", "ağrı", "burdur", "gaziantep", "hatay", "istanbul", "kahramanmaraş", "konya", "mersin", "tokat", "uşak", "van", "zonguldak" }));
        jcombo_il.setToolTipText("");
        jcombo_il.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo_ilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jl_telefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(tc_kimlik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jl_cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtex_sifre_tekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtex_soyisim, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtex_isim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                                    .addComponent(jtex_tc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jformtex_dogum)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jradio_erkek)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(jradio_kadın, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtex_email)
                                    .addComponent(jtex_kullanici_adi)
                                    .addComponent(jtex_sifre)
                                    .addComponent(jtex_meslek)
                                    .addComponent(jtex_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jcombo_il, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_temizle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_kapat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_kaydol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel_girisegider, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_kaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(button_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tc_kimlik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtex_tc, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtex_isim, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtex_soyisim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jl_telefon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtex_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtex_meslek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcombo_il, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jformtex_dogum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtex_email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jradio_erkek)
                            .addComponent(jradio_kadın))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtex_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtex_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtex_sifre_tekrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jlabel_girisegider, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel2AncestorMoved

    private void button_kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kaydolActionPerformed

        baglanti_olustur();
        //kayitformundaki boş alanları tespit etme
        String tckimlik=jtex_tc.getText();
        String isim=jtex_isim.getText();
        String soyisim=jtex_soyisim.getText();
        String telefon=jtex_telefon.getText();
        String meslek=jtex_meslek.getText();
        String dogumTarihi=jformtex_dogum.getText();
        String email=jtex_email.getText();
        String kullanici_adi=jtex_kullanici_adi.getText();
        String sifre= jtex_sifre.getText();
        String sifreTekrar=jtex_sifre_tekrar.getText();
        
        if(tckimlik.isEmpty() || isim.isEmpty() || soyisim.isEmpty() || telefon.isEmpty() || meslek.isEmpty() || dogumTarihi.isEmpty() || email.isEmpty() ||
                kullanici_adi.isEmpty() || sifre.isEmpty() || sifreTekrar.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Formun Tamamını Doldurun","Hata",JOptionPane.ERROR_MESSAGE);
            
        }
        else if(!sifre.equals(sifreTekrar)){
            JOptionPane.showMessageDialog(this,"Şifreler Eşleşmiyor!","Hata",JOptionPane.ERROR_MESSAGE);
           
        }
        else{
            JOptionPane.showMessageDialog(this,"Kayıt Oluşturuldu/Ana Sayfaya Yönlendiriliyorsunuz..","KAYIT BAŞARILI",JOptionPane.PLAIN_MESSAGE);
            new genelbakis().setVisible(true);
            ekle();
            dispose();
        }
         baglanti_kapat();
    }//GEN-LAST:event_button_kaydolActionPerformed
        public boolean kullaniciadi_kontrol(String kullanici_adi){
            baglanti_olustur();
            PreparedStatement st = null;
            ResultSet rs;
            
            boolean kullanici_adi_exist=false;
            
            String query= "SELECT * FROM `kayit` WHERE `kullanici_adi` = ?";
           try{
               baglanti_olustur();
               st.setString(1, kullanici_adi);
               rs=st.executeQuery();
               
               if(rs.next()){
                   kullanici_adi_exist=true;
                   JOptionPane.showMessageDialog(null,"Bu Kullanıcı Adı Zaten Mevcut","Hata",2);
               }
               
           } catch(SQLException ex){
             Logger.getLogger(kayitFormu.class.getName()).log(Level.SEVERE, null, ex);
           }
           return kullanici_adi_exist;
        }
    private void button_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kapatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_kapatActionPerformed

    private void jtex_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_emailActionPerformed

    private void button_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_temizleActionPerformed
        // TODO add your handling code here:
      temizle();
    }//GEN-LAST:event_button_temizleActionPerformed

    private void jtex_isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_isimActionPerformed

    private void jlabel_girisegiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_girisegiderMouseClicked
        // TODO add your handling code here:
        girisyapmaekrani grs= new girisyapmaekrani();
        grs.setVisible(true);
        grs.pack();
        grs.setLocationRelativeTo(null);
        grs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jlabel_girisegiderMouseClicked

    private void jtex_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_tcActionPerformed

    private void jtex_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_sifreActionPerformed

    private void jradio_kadınActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_kadınActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradio_kadınActionPerformed

    private void jtex_meslekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtex_meslekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtex_meslekActionPerformed

    private void jcombo_ilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo_ilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombo_ilActionPerformed

    private void jtex_telefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtex_telefonKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtex_telefonKeyTyped

    //aynı kullanıcı adını almayı engelleme

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new kayitFormu().setVisible(true);
            }
        });
    }
   public void baglanti_olustur(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            baglanti = DriverManager.getConnection(link,kullanici_adi,sifre);
            //JOptionPane.showMessageDialog(null, "Bağlanti başarılı");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(kayitFormu.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(kayitFormu.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public void baglanti_kapat(){
        try {
            baglanti.close();
        } catch (SQLException ex) {
            Logger.getLogger(kayitFormu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void ekle(){
        String t2,t3,t5,t7,t8,t10,t11,t12;
        long tckimlik;
        long telefon;
        
        t2=jtex_isim.getText();
        t3=jtex_soyisim.getText();
        t5=jtex_meslek.getText();
        t7=jformtex_dogum.getText();
        t8=jtex_email.getText();
        t10=jtex_kullanici_adi.getText();
        t11=jtex_sifre.getText();
        t12=jtex_sifre_tekrar.getText();
        
       tckimlik=Long.parseLong(jtex_tc.getText().trim()); 
       telefon=Long.parseLong(jtex_telefon.getText().trim());
        
       
        String cinsiyet= "";
        String yasanilanSehir="";
        
        if(jradio_kadın.isSelected()==true)
        {
            cinsiyet="KADIN";
        }
        if(jradio_erkek.isSelected()==true){
            cinsiyet="ERKEK";
        }
        if(jcombo_il.getSelectedIndex()==0){
            yasanilanSehir="adana";
        }
         if(jcombo_il.getSelectedIndex()==1){
            yasanilanSehir="ağrı";
        }
          if(jcombo_il.getSelectedIndex()==2){
            yasanilanSehir="burdur";
        }
           if(jcombo_il.getSelectedIndex()==3){
            yasanilanSehir="gaziantep";
        }
            if(jcombo_il.getSelectedIndex()==4){
            yasanilanSehir="hatay";
        }
             if(jcombo_il.getSelectedIndex()==5){
            yasanilanSehir="istanbul";
        }
              if(jcombo_il.getSelectedIndex()==6){
            yasanilanSehir="kahramanmaraş";
        }
               if(jcombo_il.getSelectedIndex()==7){
            yasanilanSehir="konya";
        }
                if(jcombo_il.getSelectedIndex()==8){
            yasanilanSehir="mersin";
        }
                 if(jcombo_il.getSelectedIndex()==9){
            yasanilanSehir="tokat";
        }
                  if(jcombo_il.getSelectedIndex()==10){
            yasanilanSehir="uşak";
        }
                   if(jcombo_il.getSelectedIndex()==11){
            yasanilanSehir="van";
        }
                    if(jcombo_il.getSelectedIndex()==12){
            yasanilanSehir="zonguldak";
        }
                    
        
        String eklesorgusu="INSERT INTO kayit (tckimlik,isim,soyisim,telefon,meslek,yasanilanSehir,dogumTarihi,email,cinsiyet,kullanici_adi,sifre,sifreTekrar) values("+tckimlik+",'"+t2+"','"+t3+"','"+telefon+"','"+t5+"','"+yasanilanSehir+"','"+t7+"','"+t8+"','"+cinsiyet+"','"+t10+"','"+t11+"','"+t12+"')";
        
       try{
           
          
           Statement abc=baglanti.createStatement();
           abc.execute(eklesorgusu);
           System.out.println("veritabanına veri eklendi");
       }
           
       catch(SQLException ex){
           System.out.println(ex.toString());
           System.out.println("veritabanına veri eklenemedi");
       }

        
    }
   /* public void bul() 
    {
        try{
            Statement sta=baglanti.createStatement();
            String bulkomutu="select from kayit where kullanici_adi="+jtex_kullaniciadi.getText();
            
            ResultSet res = sta.executeQuery(bulkomutu);
            res.next();
            
            String cinsiyet="";
            jtex_tc.setText(res.getString("tckimlik"));
            jtex_isim.setText(res.getString("isim"));
            jtex_soyisim.setText(res.getString("soyisim"));
            jtex_telefon.setText(res.getString("telefon"));
            jtex_meslek.setText(res.getString("meslek"));
            jtex_il.setText(res.getString("yasanilanSehir"));
            jformtex_dogum.setText(res.getString("dogumTarihi"));
            jtex_email.setText(res.getString("email"));
            jtex_sifre.setText(res.getString("sifre"));
            jtex_sifre_tekrar.setText(res.getString("sifreTekrar"));
            
            cinsiyet=res.getString("cinsiyet");
            
            if(cinsiyet.equals("KADIN")){
                jradio_kadın.setSelected(true);
            }
            if(cinsiyet.equals("ERKEK")){
                jradio_erkek.setSelected(true);
            } 
        }catch(Exception b){
            System.out.println("Kayıt Bulunurken Hata Oluştu"+b);
        }
    }
 */
    public void temizle(){
        jtex_tc.setText("");
        jtex_isim.setText("");
        jtex_soyisim.setText("");
        jtex_telefon.setText("");
        jtex_meslek.setText("");
        jformtex_dogum.setText("");
        jtex_email.setText("");
        jtex_kullanici_adi.setText("");
        jtex_sifre.setText("");
        jtex_sifre_tekrar.setText("");
        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_kapat;
    private javax.swing.JButton button_kaydol;
    private javax.swing.JButton button_temizle;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcombo_il;
    private javax.swing.JFormattedTextField jformtex_dogum;
    private javax.swing.JLabel jl_cinsiyet;
    private javax.swing.JLabel jl_telefon;
    private javax.swing.JLabel jlabel_girisegider;
    private javax.swing.JRadioButton jradio_erkek;
    private javax.swing.JRadioButton jradio_kadın;
    private javax.swing.JTextField jtex_email;
    private javax.swing.JTextField jtex_isim;
    private javax.swing.JTextField jtex_kullanici_adi;
    private javax.swing.JTextField jtex_meslek;
    private javax.swing.JTextField jtex_sifre;
    private javax.swing.JTextField jtex_sifre_tekrar;
    private javax.swing.JTextField jtex_soyisim;
    private javax.swing.JTextField jtex_tc;
    private javax.swing.JTextField jtex_telefon;
    private javax.swing.JLabel tc_kimlik;
    // End of variables declaration//GEN-END:variables
}
